# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_auto_20171203_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='estado',
            field=models.SmallIntegerField(choices=[(0, 'Activo'), (1, 'Inactivo'), (2, 'Pasante')], default=1),
        ),
        migrations.RemoveField(
            model_name='voluntario',
            name='referencia',
        ),
        migrations.AddField(
            model_name='voluntario',
            name='referencia',
            field=models.ManyToManyField(to='voluntarios.Referencia'),
        ),
    ]
